// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-venues.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_venues_default = defineTool({
  name: "list_venues",
  title: "List venues",
  description: "List venues the signed-in user can access on H&L OrderNOW.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("venues").select("id, name, cuisine_type, city, state, status").order("name").limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List recent orders",
  description: "List recent orders for a venue the signed-in user can access.",
  inputSchema: {
    venue_id: z.string().uuid().describe("Venue ID to list orders for."),
    limit: z.number().int().min(1).max(100).optional().describe("Max orders to return (default 20)."),
    status: z.string().optional().describe("Optional status filter (e.g. 'placed', 'in_progress', 'completed').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ venue_id, limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("orders").select("id, status, total_amount, created_at, table_id, diner_id").eq("venue_id", venue_id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-menu.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_menu_default = defineTool3({
  name: "get_menu",
  title: "Get menu",
  description: "Fetch menu categories and items for a venue.",
  inputSchema: {
    venue_id: z2.string().uuid().describe("Venue ID whose menu to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const [{ data: categories, error: cErr }, { data: items, error: iErr }] = await Promise.all([
      sb.from("menu_categories").select("id, name, display_order").eq("venue_id", venue_id).order("display_order"),
      sb.from("menu_items").select("id, name, description, price, category_id, is_available").eq("venue_id", venue_id).order("name")
    ]);
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (iErr) return { content: [{ type: "text", text: iErr.message }], isError: true };
    const menu = { categories: categories ?? [], items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(menu, null, 2) }],
      structuredContent: menu
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hjcikekaythqjhcuznjf";
var mcp_default = defineMcp({
  name: "hl-ordernow-mcp",
  title: "H&L OrderNOW",
  version: "0.1.0",
  instructions: "Tools for H&L OrderNOW venue operators. Use `list_venues` to discover venues the signed-in user manages, `get_menu` to read a venue's menu, and `list_orders` to inspect recent orders. All calls act as the authenticated user and respect the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_venues_default, get_menu_default, list_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
